config/routes.rb
Jobpage::Application.routes.draw do

  # Devise Routes
  devise_for :users #, :controllers => { :registrations => "users/registrations" }

  # Dashboard Routes
  get 'dashboard' => 'dashboard#index'
  
  namespace :dashboard do
    resources :jobs
    resources :job_applications
    get 'appearance' => 'appearance#index'
  end

  # Front Routes
  resources :jobs do
    resources :job_applications
  end
  match '', to: 'front#index', constraints: {subdomain: /.+/}, via: [:get] #Maps Subdomain User setting to subdomain page
  get 'job' => 'front#show'

  # Static_Pages Routes
  get 'about' => 'static_pages#about'
  get 'features' => 'static_pages#features'
  get 'pricing' => 'static_pages#pricing'

  # Root Route
  root 'static_pages#index'
  
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/dashboard/appearance_controller.rb
class Dashboard::AppearanceController < ApplicationController
	layout "layouts/dashboard/dashboard"

	def index	
	end
end

app/controllers/dashboard/job_applications_controller.rb
class Dashboard::JobApplicationsController < ApplicationController
  layout "layouts/dashboard/dashboard"
  before_filter :authenticate_user!
  before_action :set_job_application, only: [:show, :edit, :update, :destroy]

  # GET /job_applications
  # GET /job_applications.json
  def index
    @job_applications = current_user.job_applications.all
  end

  # GET /job_applications/1
  # GET /job_applications/1.json
  def show
    @job = current_user.job_applications.find(params[:id])
  end

  # GET /job_applications/new
  def new
    @job_application = current_user.job_applications.new
  end

  # GET /job_applications/1/edit
  def edit
  end

  # POST /job_applications
  # POST /job_applications.json
  def create
    @job_application = current_user.job_applications.new(job_application_params)

    respond_to do |format|
      if @job_application.save
        format.html { redirect_to dashboard_job_application_path(@job_application), notice: 'Job application was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job_application }
      else
        format.html { render action: 'new' }
        format.json { render json: dashboard_job_application_path(@job_application).errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /job_applications/1
  # PATCH/PUT /job_applications/1.json
  def update
    respond_to do |format|
      if @job_application.update(job_application_params)
        format.html { redirect_to dashboard_job_application_path(@job_application), notice: 'Job application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: dashboard_job_application_path(@job_application).errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /job_applications/1
  # DELETE /job_applications/1.json
  def destroy
    @job_application.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_job_applications_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_application
      @job_application = current_user.job_applications.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_application_params
      params.require(:job_application).permit(:name)
    end
end

app/controllers/dashboard/jobs_controller.rb
class Dashboard::JobsController < ApplicationController
  layout "layouts/dashboard/dashboard"
  before_filter :authenticate_user!
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = current_user.jobs.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = current_user.jobs.find(params[:id])
  end

  # GET /jobs/new
  def new
    @job = current_user.jobs.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_user.jobs.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to dashboard_job_path(@job), notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: dashboard_job_path(@job).errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to dashboard_job_path(@job), notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = current_user.jobs.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :description, :jobskills, :joblocation, :employmenttype, :joblength, :payrate, :travelrequired)
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  layout "dashboard/dashboard"
  before_filter :authenticate_user!

  def index
  end

  def company_settings
  end
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
	def dashbrand
		current_user.company_name || 'Jobbster'
	end

	def frontlink
		if :subdomain
			root_url(subdomain: current_user.subdomain)
		else
			dashboard_path
		end
	end
end

app/views/layouts/dashboard/_footer.html.erb
<hr />
<div class="footer">
  <small>
    <%= link_to "Pathwall", 'root_path' %> &copy; 2013
  </small>
</div>

app/views/layouts/dashboard/_header.html.erb
<div class="container">
  <div class="navbar">
    <div class="navbar-inner">
        
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             <%= link_to dashbrand, frontlink, target: "_blank", class: "brand" %>

                <div class="nav-collapse">
                    <ul class="nav">
                        <li>
                            <%= link_to 'Dashboard', dashboard_path %>
                        </li>
                        <li>    
                            <%= link_to "Applications", dashboard_job_applications_path %>
                        </li>
                        <li>    
                            <%= link_to "Jobs", dashboard_jobs_path %>
                        </li>
                        <li>    
                            <%= link_to "Appearance", dashboard_appearance_path %>
                        </li>
                    </ul>
                    <ul class="nav pull-right">
                    <li id="fat-menu" class="dropdown">
                      <a href="#" id="drop3" role="button" class="dropdown-toggle" data-toggle="dropdown">User <b class="caret"></b></a>
                      <ul class="dropdown-menu" role="menu" aria-labelledby="drop3">
                        <li role="presentation"><%= link_to 'Edit Account', edit_user_registration_path %></a></li>
                        <li role="presentation" class="divider"></li>
                        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                      </ul>
                    </li>
                  </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/dashboard/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PathWall - Dashboard</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/dashboard/header' %>
    <div class="container">
      <%= render 'layouts/dashboard/flash' %>
      <%= yield %>
      <%= render 'layouts/dashboard/footer' %>
    </div>

  </body>
</html>