config/routes.rb
Jobpage::Application.routes.draw do

  # Devise Routes
  devise_for :users #, :controllers => { :registrations => "users/registrations" }

  # Dashboard Routes
  get 'dashboard' => 'dashboard#index'
  
  namespace :dashboard do
    resources :jobs
    resources :job_applications
    get 'appearance' => 'appearance#index'
  end

  # Front Routes
  resources :jobs do
    resources :job_applications
  end
  match '', to: 'front#index', constraints: {subdomain: /.+/}, via: [:get] #Maps Subdomain User setting to subdomain page
  get 'job' => 'front#show'

  # Static_Pages Routes
  get 'about' => 'static_pages#about'
  get 'features' => 'static_pages#features'
  get 'pricing' => 'static_pages#pricing'

  # Root Route
  root 'static_pages#index'
  
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  has_many :job_applications
  accepts_nested_attributes_for :job_applications
end

app/controllers/dashboard/jobs_controller.rb
class Dashboard::JobsController < ApplicationController
  layout "layouts/dashboard/dashboard"
  before_filter :authenticate_user!
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = current_user.jobs.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = current_user.jobs.find(params[:id])
  end

  # GET /jobs/new
  def new
    @job = current_user.jobs.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = current_user.jobs.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to dashboard_job_path(@job), notice: 'Job was successfully created.' }
        format.json { render action: 'show', status: :created, location: @job }
      else
        format.html { render action: 'new' }
        format.json { render json: dashboard_job_path(@job).errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to dashboard_job_path(@job), notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_jobs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = current_user.jobs.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :description, :jobskills, :joblocation, :employmenttype, :joblength, :payrate, :travelrequired)
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  layout "front/front"
  before_filter :load_biz
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  def index
    @jobs = @biz.jobs.all
  end

  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = @biz.jobs.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :description, :job_application)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/index.html.erb
<h1>Job Listings</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.name %></td>
        <td><%= job.description %></td>
        <td><%= link_to 'Show', job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= job.user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_job_path, class: 'btn' %>

app/views/jobs/new.html.erb
<%= render 'form' %>

app/views/jobs/show.html.erb
<p>
  <strong>Title</strong><br />
  <%= @job.name %>
</p>
<p>
  <strong>Job Description</strong><br />
  <%= @job.description %>
</p>
<p>
  <strong>Job Skills</strong><br />
  <%= @job.jobskills %>
</p>
<p>
  <strong>Job Location</strong><br />
  <%= @job.joblocation %>
</p>
<p>
  <strong>Employment Type</strong><br />
  <%= @job.employmenttype %>
</p>
<p>
  <strong>Job Length</strong><br />
  <%= @job.joblength %>
</p>
<p>
  <strong>Pay Rate</strong><br />
  <%= @job.payrate %>
</p>
<p>
  <strong>Travel Required</strong><br />
  <%= @job.travelrequired %>
</p>

<%= link_to 'Apply For This Job', new_job_job_application_path(@job), class: 'btn' %>