config/routes.rb
Jobpage::Application.routes.draw do

  # Devise Routes
  devise_for :users #, :controllers => { :registrations => "users/registrations" }

  # Dashboard Routes
  get 'dashboard' => 'dashboard#index'
  
  namespace :dashboard do
    resources :jobs
    resources :job_applications
    get 'appearance' => 'appearance#index'
  end

  # Front Routes
  resources :jobs do
    resources :job_applications
  end
  match '', to: 'front#index', constraints: {subdomain: /.+/}, via: [:get] #Maps Subdomain User setting to subdomain page
  get 'job' => 'front#show'

  # Static_Pages Routes
  get 'about' => 'static_pages#about'
  get 'features' => 'static_pages#features'
  get 'pricing' => 'static_pages#pricing'

  # Root Route
  root 'static_pages#index'
  
  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end
  
  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    <%= link_to "Jobbster", '#' %>
    by <%= link_to "Julian Salas", "http://juliansalas.com" %>
  </small>
</div>

app/views/layouts/_header.html.erb
<div class="container">
  <div class="navbar">
    <div class="navbar-inner">
        
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
             <a class="brand" href="/">Pathwall</a>

                <div class="nav-collapse">
                    <ul class="nav">
                        <li>
                            <%= link_to 'Home',  root_path %>
                        </li>
                        <li>    
                            <%= link_to 'About',  about_path %>
                        </li>
                        <li>    
                            <%= link_to 'Features',  features_path %>
                        </li>
                        <li>    
                            <%= link_to 'Pricing',  pricing_path %>
                        </li>
                    </ul>
                    <ul class="nav pull-right">
                      <% if user_signed_in? %>
                        <li><%= link_to "Dashboard", dashboard_path %></li>
                      <% else %>
                      <li><%= link_to "Sign Up", new_user_registration_path %></li>
                      <li><%= link_to "Login", new_user_session_path %></li>
                      <% end %>
            </ul>
                </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pathwall - Home</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>

  </body>
</html>